version: '3.8'

services:
  web:
    build: .
    command: gunicorn medirc_backend.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  worker:
    build: .
    command: python manage.py process_tasks
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MEDIREC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  postgres_data:
