version: '3.8'

services:
  web:
    build: .
    command: gunicorn medirc_backend.wsgi:application --bind 0.0.0.0:5000  # Changed port to 5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # Exposing port 5000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MEDIREC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
